name: 'clang-tidy-native'
description: 'Runs clang-tidy on the codebase'

inputs:
  build-dir:
    description: 'Build directory'
    required: true
    default: 'build'
  cmake-defs:
    description: 'Additional CMake definitions'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Run clang-tidy
      shell: bash
      run: |
        cd ${{ inputs.build-dir }} && run-clang-tidy
