name: 'clang-tidy-native'
description: 'Runs clang-tidy on the codebase'

inputs:
  build_dir:
    description: 'Build directory'
    required: true
    default: 'build'
  cmake-defs:
    description: 'Additional CMake definitions'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Configure CMake with compile commands
      shell: bash
      run: |
        cmake -B ${{ inputs.build_dir }} -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ${{ inputs.cmake-defs }}

    - name: Copy compilation database to root
      shell: bash
      run: |
        cp ${{ inputs.build_dir }}/compile_commands.json ./

    - name: Run clang-tidy from project root
      shell: bash
      run: |
        run-clang-tidy
